/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication5;

import java.awt.*;
import java.awt.event.*;
import java.applet.Applet.*;


/**
 *
 * @author BHARATH RAJ
 */
public class ColorPalette extends java.applet.Applet implements ActionListener,ItemListener{

    private static final long serialVersionUID = 1L;

Button[] colors;
Panel buttonpanel;
TextArea txtaComments;
CheckboxGroup cbgColor;
CheckboxGroup cbgImage;
Checkbox optFore,optBack;
Checkbox optMb,optCatn;
Image imgMb,imgCatn;
String colour;

    /**
     *
     */
    @Override
    public void init() {
        setLayout(new GridLayout(5,2));
buttonpanel=new Panel();
buttonpanel.setLayout(new GridLayout(3,3));
colors=new Button[9];
colors[0]=new Button("RED");
colors[1]=new Button("GREEN");
colors[2]=new Button("BLUE");
colors[3]=new Button("CYAN");
colors[4]=new Button("ORANGE");
colors[5]=new Button("WHITE");
colors[6]=new Button("BLACK");
colors[7]=new Button("YELLOW");
colors[8]=new Button("PINK");
for(int i=0;i<9;i++)
{
colors[i].addActionListener(this);
buttonpanel.add(colors[i]);
}
txtaComments = new TextArea("Enter Your Text Here!", 5, 30);
cbgColor = new CheckboxGroup();
cbgImage = new CheckboxGroup();
optFore = new Checkbox("Foreground", cbgColor,true);
optBack = new Checkbox("Background", cbgColor,false);
optMb = new Checkbox("MEC-Admin Block", cbgImage,true);
optCatn = new Checkbox("MEC CANTEEN",cbgImage, false);
imgMb = getImage (getDocumentBase(), getParameter("mecadmin"));
imgCatn = getImage (getDocumentBase(), getParameter("meccanteen"));
add(buttonpanel);
add(txtaComments);
add(optFore);
add(optBack);
add(optMb);
add(optCatn);
optFore.addItemListener(this);
optBack.addItemListener(this);
optMb.addItemListener(this);
optCatn.addItemListener(this);
}
    public Color getColour()
{
Color mycolor=null;
if (colour.equals("RED"))
{
mycolor=Color.red;
}
if(colour.equals("GREEN"))
{
mycolor=Color.green;
}
if(colour.equals("BLUE"))
{
mycolor=Color.blue;
}
if(colour.equals("CYAN"))
{
mycolor=Color.cyan;
}
if(colour.equals("ORANGE"))
{
mycolor=Color.orange;
}
if(colour.equals("WHITE"))
{
mycolor=Color.white;
}
if(colour.equals("BLACK"))
{
mycolor=Color.black;
}
if(colour.equals("YELLOW"))
{
mycolor=Color.yellow;
}
if(colour.equals("PINK"))
{
mycolor=Color.pink;
}
return mycolor;
}

    /**
     *
     * @param ie
     */
    @Override
public void itemStateChanged(ItemEvent ie)
{
repaint();
}
@Override
public void paint(Graphics g)
{
if (optMb.getState() == true)
{
g.drawImage(imgMb, 200, 400, this) ;
}
if (optCatn.getState() == true)
{
g.drawImage(imgCatn, 200, 400, this) ;
}
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>                        

    @Override
    public void actionPerformed(ActionEvent ae) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }


    // Variables declaration - do not modify                     
    // End of variables declaration                   
}
